#!/usr/bin/env python3
"""
Analyze the Triton kernels generated by torch.compile
"""

import os
import glob

kernel_dir = "torch_compile_kernels/triton/0"

print("=" * 80)
print("TRITON KERNELS GENERATED BY TORCH.COMPILE")
print("=" * 80)
print()

# Find all kernel directories
kernel_dirs = glob.glob(f"{kernel_dir}/*/")

print(f"Found {len(kernel_dirs)} kernels")
print()

for i, kdir in enumerate(kernel_dirs, 1):
    print("=" * 80)
    print(f"KERNEL {i}/{len(kernel_dirs)}")
    print("=" * 80)
    print()

    # Find Python files
    py_files = glob.glob(f"{kdir}/*.py")

    if not py_files:
        print("No Python files found")
        continue

    py_file = py_files[0]
    print(f"File: {os.path.basename(py_file)}")
    print(f"Path: {py_file}")
    print()

    # Read and analyze
    with open(py_file, 'r') as f:
        code = f.read()

    # Extract key information
    lines = code.split('\n')

    # Find function definition
    for line in lines:
        if 'def triton_' in line or 'def kernel' in line:
            print(f"Function: {line.strip()}")
            print()
            break

    # Count operations
    operations = {
        'loads': code.count('tl.load'),
        'stores': code.count('tl.store'),
        'max': code.count('tl.max') + code.count('.maximum'),
        'sum': code.count('tl.sum'),
        'sqrt': code.count('tl.sqrt'),
        'where': code.count('tl.where'),
        'div': code.count(' / '),
        'mul': code.count(' * '),
        'sub': code.count(' - '),
    }

    print("Operations in this kernel:")
    for op, count in operations.items():
        if count > 0:
            print(f"  {op:10s}: {count}")
    print()

    # Show first 60 lines
    print("Code preview (first 60 lines):")
    print("-" * 80)
    for j, line in enumerate(lines[:60], 1):
        print(f"{j:3d} | {line}")

    if len(lines) > 60:
        print(f"    | ... ({len(lines) - 60} more lines)")

    print()
    print()

print("=" * 80)
print("ANALYSIS")
print("=" * 80)
print()

# Try to identify kernel purposes based on operations
print("Kernel roles (estimated based on operations):")
print()

for i, kdir in enumerate(kernel_dirs, 1):
    py_files = glob.glob(f"{kdir}/*.py")
    if not py_files:
        continue

    with open(py_files[0], 'r') as f:
        code = f.read()

    # Guess what this kernel does
    has_max = 'tl.max' in code or '.maximum' in code
    has_sum = 'tl.sum' in code
    has_sqrt = 'tl.sqrt' in code
    has_where = 'tl.where' in code
    has_div = ' / ' in code
    loads = code.count('tl.load')
    stores = code.count('tl.store')

    purpose = "Unknown"

    if has_max and not has_where and loads == 1:
        purpose = "Max reduction"
    elif has_sqrt and has_sum:
        purpose = "Std/Variance reduction"
    elif has_where and has_div:
        purpose = "Pointwise: scale + filter"
    elif has_sum and not has_sqrt:
        purpose = "Sum reduction"

    print(f"Kernel {i}: {purpose}")
    print(f"  Loads: {loads}, Stores: {stores}")
    print(f"  Operations: ", end="")
    ops = []
    if has_max: ops.append("max")
    if has_sum: ops.append("sum")
    if has_sqrt: ops.append("sqrt")
    if has_where: ops.append("where")
    if has_div: ops.append("div")
    print(", ".join(ops) if ops else "none")
    print()

print()
print("To view full kernel code:")
print("  cat torch_compile_kernels/triton/0/<hash>/*.py")
print()
