#!/bin/bash
# Show all Triton kernels generated by torch.compile

echo "========================================================================="
echo "TORCH.COMPILE GENERATED KERNELS"
echo "========================================================================="
echo ""

count=1
for kernel_dir in torch_compile_kernels/triton/0/*/; do
    echo "Kernel $count: $(basename $kernel_dir)"
    echo "-------------------------------------------------------------------------"

    # Find .py files
    py_files=$(find "$kernel_dir" -name "*.py" | head -1)

    if [ -n "$py_files" ]; then
        # Show function signature and first 50 lines
        echo "File: $(basename $py_files)"
        echo ""
        head -80 "$py_files"
        echo ""
        echo "... (truncated, run 'cat $py_files' to see full kernel)"
        echo ""
    else
        echo "No .py files found"
        echo ""
    fi

    echo ""
    count=$((count + 1))
done

echo "========================================================================="
echo "SUMMARY"
echo "========================================================================="
echo ""
echo "Total kernels generated: $((count - 1))"
echo ""
echo "To view a specific kernel in full:"
echo "  cat torch_compile_kernels/triton/0/<hash>/triton_*.py"
echo ""
